### ISSUE TITLE
Updating the SolidusAftepay::PaymentMethod sets the minimum_amount and maximum_amount preferences to 0.0

### ISSUE THREAD

**Issue by ChristianRimondi** [nebulab/solidus_afterpay#18]
Updating the `SolidusAftepay::PaymentMethod` sets the `minimum_amount` and `maximum_amount` preferences to `0.0` instead of leaving them `nil`. This is causing an issue [here](https://github.com/nebulab/solidus_afterpay/blob/main/app/models/solidus_afterpay/payment_method.rb#L42-L43) because instead of retrieving the configuration from Afterpay, the method always returns  a `0.0..0.0` range.

**Comment by vassalloandrea** [comment]
This should be the correct behavior: 

- if the minimum and maximum are set inside the admin, use these values to show or not the payment methods
- if the minimum and maximum are not set inside the admin, do not set it to 0 but fetch this information from Afterpay

An additional goal is: fetch the information from Afterpay and cache them for 1 day.
